name: Integration tests

# on:
#   pull_request:
#     branches:
#       - master
on: [push]

jobs:
  integration-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install build-essential and python
        run: sudo apt-get install -y build-essential python awscli
      - name: Create AWS CLI config file
        run: mkdir -p ~/.aws && echo "[default]\nregion=${{ secrets.AWS_REGION }}" | tee ~/.aws/config
      - name: Create AWS CLI credentials file
        run: echo "[encrypted]\naws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}\naws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" | tee ~/.aws/credentials
      - name: Checkout
        uses: actions/checkout@v1
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install dependencies and build
        run: |
          npm install
          npm run test:setup-ci
      - name: Cypress run
        uses: cypress-io/github-action@v1
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        with:
          start: npm run start
          wait-on: 'http://localhost:8080'
          wait-on-timeout: 120
